---
- name: Template Lunie service file
  template:
    src: "lunie.service.j2"
    dest: "/etc/systemd/system/lunie.service"
  become: true


- name: Clone lunie
  git:
    repo: "https://github.com/luniehq/lunie"
    dest: "/var/lunie"
    update: yes
    force: yes

- name: Build site
  shell: "cd /var/lunie && npm install && STARGATE=https://lunie.coinos.io RPC=https://lunie.coinos.io:26657 npm run build:ui"

- name: Set lunie to run on startup
  systemd:
    daemon_reload: yes
    name: lunie
    state: restarted
    enabled: yes
  become: true

- name: Wait for Quick crashes
  pause:
    seconds: 5

- name: Check if lunie is running
  command: systemctl status lunie
  ignore_errors: yes
  changed_when: false
  register: service_lunie_status

- name: Report status of lunie
  fail:
    msg: |
      Service lunie is not running.
      Output of `systemctl status lunie`:
      {{ service_lunie_status.stdout }}
      {{ service_lunie_status.stderr }}
  when: service_lunie_status is failed
