---
- name: Template main nginx config
  template:
    src: "nginx.conf"
    dest: "/etc/nginx/nginx.conf"
  become: true

- name: Template nginx configs
  template:
    src: "{{item}}"
    dest: "/etc/nginx/sites-enabled/{{item}}"
  become: true
  with_items:
    - lunie.conf

- name: Set Nginx to run on startup
  systemd:
    name: nginx
    state: restarted
    enabled: yes
  become: true
